/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// Stub file for local builds without Amplify environment variables.

const awsmobile = {
  aws_project_region: process.env.REACT_APP_AWS_REGION || 'us-east-1',
  aws_cognito_region: process.env.REACT_APP_AWS_REGION || 'us-east-1',
  aws_user_pools_id: process.env.REACT_APP_USER_POOLS_ID || '',
  aws_user_pools_web_client_id: process.env.REACT_APP_USER_POOLS_WEB_CLIENT_ID || '',
  aws_mandatory_sign_in: 'enable',
  aws_user_files_s3_bucket: process.env.REACT_APP_BUCKET_NAME || '',
  aws_user_files_s3_bucket_region: process.env.REACT_APP_AWS_REGION || 'us-east-1',
};

export default awsmobile;
